definitions:
  models.Admin:
    properties:
      _id:
        type: string
      created_at:
        type: string
      email:
        type: string
      password:
        type: string
      token:
        type: string
      updated_at:
        type: string
      user_name:
        type: string
    required:
    - email
    - password
    - user_name
    type: object
  models.AvailableExams:
    properties:
      _id:
        type: string
      created_at:
        type: string
      dates:
        items:
          type: string
        type: array
      exam_type:
        $ref: '#/definitions/models.ExamTypeDetails'
      months:
        items:
          type: string
        type: array
      updated_at:
        type: string
    required:
    - dates
    - exam_type
    - months
    type: object
  models.CreateAdminRequest:
    properties:
      email:
        type: string
      password:
        type: string
      user_name:
        type: string
    required:
    - email
    - password
    - user_name
    type: object
  models.CreateAvailableExamRequest:
    properties:
      dates:
        items:
          type: string
        type: array
      exam_type:
        type: string
      months:
        items:
          type: string
        type: array
    required:
    - dates
    - exam_type
    - months
    type: object
  models.CreateUserRequest:
    properties:
      day:
        type: string
      dob:
        type: string
      email:
        type: string
      exam_id:
        type: string
      month:
        type: string
      name:
        type: string
      prometric_id:
        type: string
      prometric_password:
        type: string
    required:
    - day
    - dob
    - email
    - exam_id
    - month
    - name
    - prometric_id
    - prometric_password
    type: object
  models.Exam:
    properties:
      _id:
        type: string
      created_at:
        type: string
      exam_type:
        type: string
      section:
        items:
          type: string
        type: array
      updated_at:
        type: string
    required:
    - exam_type
    type: object
  models.ExamTypeDetails:
    properties:
      _id:
        type: string
      exam_type:
        type: string
      section:
        items:
          type: string
        type: array
    required:
    - exam_type
    type: object
  models.ForgotPasswordRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  models.ForgotPasswordUpdateRequest:
    properties:
      confirm_password:
        type: string
      email:
        type: string
      password:
        type: string
    required:
    - confirm_password
    - email
    - password
    type: object
  models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.RefreshTokenRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  models.UpdateUserRequest:
    properties:
      status:
        type: string
    required:
    - status
    type: object
  models.User:
    properties:
      _id:
        type: string
      created_at:
        type: string
      day:
        type: string
      dob:
        type: string
      email:
        type: string
      exam_id:
        type: string
      month:
        type: string
      name:
        type: string
      prometric_id:
        type: string
      prometric_password:
        type: string
      status:
        type: string
      updated_at:
        type: string
    required:
    - day
    - dob
    - email
    - exam_id
    - month
    - name
    - prometric_id
    - prometric_password
    - status
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Testing Swagger APIs.
  termsOfService: http://swagger.io/terms/
  title: Exam Data Collector API
  version: "1.0"
paths:
  /api/admins/{id}/get_admin:
    get:
      consumes:
      - application/json
      description: Get admin detail
      parameters:
      - description: Admin ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Admin'
      security:
      - JWT: []
      summary: Get admin
      tags:
      - Admins
  /api/admins/create_admin:
    post:
      consumes:
      - application/json
      description: Create a new admin in the system
      parameters:
      - description: Admin
        in: body
        name: admin
        required: true
        schema:
          $ref: '#/definitions/models.CreateAdminRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Admin'
      security:
      - JWT: []
      summary: Create a new admin
      tags:
      - Admins
  /api/admins/forgot_password:
    post:
      consumes:
      - application/json
      description: Send mail to forgot password mail
      parameters:
      - description: Admin
        in: body
        name: admin
        required: true
        schema:
          $ref: '#/definitions/models.ForgotPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Email sent successfully
          schema:
            type: string
      security:
      - JWT: []
      summary: AdminForgotPassword - Admin forgot password
      tags:
      - Admins
  /api/admins/get_all_admins:
    get:
      consumes:
      - application/json
      description: Get a list of admins
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Admin'
            type: array
      summary: Get all admins
      tags:
      - Admins
  /api/admins/login:
    post:
      consumes:
      - application/json
      description: Admin Login
      parameters:
      - description: Admin
        in: body
        name: admin
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Admin'
      tags:
      - Admins
  /api/admins/refresh_token:
    post:
      consumes:
      - application/json
      description: Admin Refresh Token
      parameters:
      - description: Admin
        in: body
        name: admin
        required: true
        schema:
          $ref: '#/definitions/models.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Admin'
      tags:
      - Admins
  /api/admins/update_password:
    post:
      consumes:
      - application/json
      description: Admin Password Update
      parameters:
      - description: Admin
        in: body
        name: admin
        required: true
        schema:
          $ref: '#/definitions/models.ForgotPasswordUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Password updated successfully
          schema:
            type: string
      security:
      - JWT: []
      tags:
      - Admins
  /api/available_exams/{id}/delete_available_exam:
    delete:
      consumes:
      - application/json
      description: Delete a available exam
      parameters:
      - description: Available Exam ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Available exam data deleted successfully
          schema:
            type: string
      security:
      - JWT: []
      summary: Delete a available exam
      tags:
      - Available_Exams
  /api/available_exams/{id}/get_available_exam:
    get:
      consumes:
      - application/json
      description: Get available exam detail
      parameters:
      - description: Available Exam ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AvailableExams'
      security:
      - JWT: []
      summary: Get available exam
      tags:
      - Available_Exams
  /api/available_exams/create_available_exam:
    post:
      consumes:
      - application/json
      description: Create a new available exam in the system
      parameters:
      - description: Available_Exams
        in: body
        name: available_exam
        required: true
        schema:
          $ref: '#/definitions/models.CreateAvailableExamRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AvailableExams'
      security:
      - JWT: []
      summary: Create a new available exam
      tags:
      - Available_Exams
  /api/available_exams/get_all_available_exams:
    get:
      consumes:
      - application/json
      description: Get a list of available exam
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.AvailableExams'
            type: array
      security:
      - JWT: []
      summary: Get all available exams
      tags:
      - Available_Exams
  /api/customers/{id}/get_customer:
    get:
      consumes:
      - application/json
      description: Get user detail
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      security:
      - JWT: []
      summary: Get user
      tags:
      - Users
  /api/customers/{id}/update_customer:
    put:
      consumes:
      - application/json
      description: User update
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      security:
      - JWT: []
      tags:
      - Users
  /api/customers/create_customer:
    post:
      consumes:
      - application/json
      description: Create a new user in the system
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Create a new user
      tags:
      - Users
  /api/customers/delete_customers:
    delete:
      consumes:
      - application/json
      description: Delete multiple users
      parameters:
      - description: Array of User IDs
        in: body
        name: ids
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: Users deleted successfully
          schema:
            type: string
      security:
      - JWT: []
      summary: Delete multiple users
      tags:
      - Users
  /api/customers/get_all_customers:
    get:
      consumes:
      - application/json
      description: Get a list of users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
      security:
      - Bearer: []
      summary: Get all users
      tags:
      - Users
  /api/exams/{id}/get_exam:
    get:
      consumes:
      - application/json
      description: Get exam detail
      parameters:
      - description: Exam ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Exam'
      security:
      - JWT: []
      summary: Get exam
      tags:
      - Exams
  /api/exams/create_exams:
    post:
      consumes:
      - application/json
      description: Create exams
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Exam'
            type: array
      security:
      - JWT: []
      summary: Create exams
      tags:
      - Exams
  /api/exams/get_all_exams:
    get:
      consumes:
      - application/json
      description: Get a list of exams
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Exam'
            type: array
      security:
      - JWT: []
      summary: Get all exams
      tags:
      - Exams
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
